KEYWORDS_LIST = [
    "`show chassis inventory expand`",
    "`show chassis inventory detail`",
    "`show chassis detail`",
    "`show chassis iom detail`",
    "`show chassis psu`",
    "`show chassis psu detail`",
    "`show iom health status detail`",
    "`show server inventory expand`",
    "`show server status detail`",
    "`show server health status detail`",
    "`show server memory detail`",
    "`show fault detail`",
    "`show fabric-interconnect detail`",
    "`show fabric-interconnect inventory expand`",
    "`show fex detail`",
    "`show fex inventory expand detail`",
    "`show event detail`",
    "`scope monitoring`",
    "`show post detail`",
    "`scope system`",
    "`scope system`",
    "`scope system`",
    "`scope services`",
    "`scope fabric-interconnect a`",
    "`scope fabric-interconnect b`",
    "`show firmware`",
    "`show service-pack version`",
    "`show vlan-port-count expand detail`",
    "`show fan detail`",
    "`show psu detail`",
    "`show storage detail`",
    "`show stats env-stats`",
    "`show stats system-stats`",
    "`show stats history system-stats`",
    "`show fsm status`",
    "`show image`",
    "`scope security`",
    "`scope security`",
    "`scope security`",
    "`scope radius`",
    "`scope tacacs`",
    "`show detail`",
    "`scope ldap`",
    "`show system firmware expand detail`",
    "`show chassis firmware detail`",
    "`show package detail`",
    "`show server environment`",
    "`show service-profile assoc`",
    "`show service-profile status`",
    "`show service-profile identity`",
    "`show service-profile connectivity`",
    "`show service-profile circuit`",
    "`show service-profile path`",
    "`scope org`",
    "`show san-connectivity-policy detail expand`",
    "`show vnic-templ detail expand`",
    "`show vhba-templ detail expand`",
    "`show fc-zone detail`",
    "`show storage-connection-policy detail expand`",
    "`scope sysdebug`",
    "`show cores detail`",
    "`show timezone`",
    "`show clock`",
    "`show domain-name`",
    "`scope license`",
    "`show feature detail`",
    "`scope license`",
    "`show file detail`",
    "`scope license`",
    "`show usage detail`",
    "`scope power-cap-mgmt`",
    "`show cap-policy`",
    "`scope power-cap-mgmt`",
    "`show profile-policy`",
    "`scope power-cap-mgmt`",
    "`show power-group`",
    "`scope power-cap-mgmt`",
    "`show power-budget`",
    "`scope power-cap-mgmt`",
    "`show power-measured`",
    "`scope power-cap-mgmt`",
    "`show power-group detail expand`",
    "`scope power-cap-mgmt`",
    "`show power-budget detail`",
    "`show firmware monitor UCSM`",
    "`scope firmware`",
    "`scope auto-install`",
    "`show top`",
    "`show service-pack version`",
    "`scope system`",
    "`show system version`",
    "`show health-led expand detail`"
]

